name: cross_platform_example
description: Demonstrates how to use the cross_platform package.

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cross_platform:
    path: ../

flutter:
  uses-material-design: true
